{% set name = "habanero" %}
{% set version = "2.2.0" %}
{% set sha256 = "18c5c3b59b8db1887811da6de8bd976ac4077d61a25a058f3a67044e8bcab8eb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - httpx >=0.27.2
    - packaging >=24.1
    - pyyaml >=6.0.2
    - tqdm >=4.66.5
    - urllib3 ==2.2.0
    - bibtexparser >=2.0.0b7

test:
  requires:
    - python {{ python_min }}
  imports:
    - habanero

about:
  home: https://github.com/sckott/habanero
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: CrossRef Search Low-level client for Python

  description: |
    This is a low level client for working with Crossref's search API.
    It's been named to be more generic, as other organizations are/will
    adopt Crossref's search API, making it possible to interact with all
    from one client.
  doc_url: http://habanero.readthedocs.io/
  dev_url: https://github.com/sckott/habanero

extra:
  recipe-maintainers:
    - bryanwweber
