{% set name = "habanero" %}
{% set version = "0.7.4" %}
{% set sha256 = "780ed450438ce671f3d6a6e4539ffcc5a11bfe08ee6d10634a0f4ab047fee0e7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/sckott/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - requests >=2.7.0
    - tqdm

test:
  imports:
    - habanero

about:
  home: https://github.com/sckott/habanero
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: CrossRef Search Low-level client for Python

  description: |
    This is a low level client for working with Crossref's search API.
    It's been named to be more generic, as other organizations are/will
    adopt Crossref's search API, making it possible to interact with all
    from one client.
  doc_url: http://habanero.readthedocs.io/
  dev_url: https://github.com/sckott/habanero

extra:
  recipe-maintainers:
    - bryanwweber
