{% set name = "habanero" %}
{% set version = "0.5.0" %}
{% set sha256 = "5c308a5ac6e25db31555354607825737f2b4b056831240bda4065a4950b22f63" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/sckott/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - requests >=2.7.0

test:
  imports:
    - habanero

about:
  home: https://github.com/sckott/habanero
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'CrossRef Search Low-level client for Python'

  description: |
    This is a low level client for working with Crossref's search API.
    It's been named to be more generic, as other organizations are/will
    adopt Crossref's search API, making it possible to interact with all
    from one client.
  doc_url: http://habanero.readthedocs.io/
  dev_url: https://github.com/sckott/habanero

extra:
  recipe-maintainers:
    - bryanwweber
