{% set name = "habanero" %}
{% set version = "2.4.0" %}
{% set sha256 = "7690ca5a261037632e5d7751ce3c47234112079ab80e9de4be626c684034e1f8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - httpx >=0.28.1
    - packaging >=26.2
    - tqdm >=4.67.3
    - urllib3 >=2.7.0,<3.0.0
    # This package isn't available on cf yet because it's still beta
    # - bibtexparser >=2.0.0b7

test:
  requires:
    - python {{ python_min }}
  imports:
    - habanero

about:
  home: https://github.com/sckott/habanero
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: CrossRef Search Low-level client for Python

  description: |
    This is a low level client for working with Crossref's search API.
    It's been named to be more generic, as other organizations are/will
    adopt Crossref's search API, making it possible to interact with all
    from one client.
  doc_url: http://habanero.readthedocs.io/
  dev_url: https://github.com/sckott/habanero

extra:
  recipe-maintainers:
    - bryanwweber
