{% set name = "habanero" %}
{% set version = "1.2.6" %}
{% set sha256 = "6250a894c2d9849a8c8f764be424256d2d8ca2d0ef0e5b6e717d89c83ecc338d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/sckott/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python
    - setuptools
    - setuptools_scm
    - pip
  run:
    - python >=3.7
    - requests >=2.7.0
    - tqdm

test:
  imports:
    - habanero

about:
  home: https://github.com/sckott/habanero
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: CrossRef Search Low-level client for Python

  description: |
    This is a low level client for working with Crossref's search API.
    It's been named to be more generic, as other organizations are/will
    adopt Crossref's search API, making it possible to interact with all
    from one client.
  doc_url: http://habanero.readthedocs.io/
  dev_url: https://github.com/sckott/habanero

extra:
  recipe-maintainers:
    - bryanwweber
