travis:
  secure:
    BINSTAR_TOKEN: IiRMiEmQ4ifc0DiYr4R4rsi7/l4MheqPGUgKBv6gmNdEJLrcATM4nQQjI7A33j6gbbOGgYZLVQbKIhJCk5YEDQsxgP5IEUfoSrG773eBJu9juOjETxmw9149lJkcprBGw9eHX+Fv+HRgKjxbmMlqIqgs/XW0aZCFamWEflLFrup+jHZgu4lUz9ch0wRExt954AE9Z6EpvCe4ZdaPf3zc0+HKhYTOnRlF88vP9tnGhr/MFlNFQOi85leX71uZ6CVuw1rbChO+9BYy9XiaD/F7xxOdVEnbGFE0kLzRqaiTMnU+GyNko3MoHe3p4SgD/u8GODonP1Ii65Pm29rlWQtEiSEa/OefDSmJR1YZt1b4FJ7v4vgMQOJKoNqTA9+95rrWwiHr+i3AK6p0JwwgH/bVgTxkh+UrK0kEH94A3IbK/uqj2VkYpSpOk0fjECenfxMWkxAo60wS9dFvUD7cWQ3aI/IRkm+z9p8opDDhts3772pWkZtdFeL82JOQlABZT1zlc/qaWsHP1/zeEROJroZQPZowsNJTPTJrvc67RN4TxGiqmUBxWA2bDU8D+I4eIY+nv9xy9SGbR+CrE8berf9pvsDtucGvU4Jvj/D5EoP27oESWQMxfiqOatmCtZqxuPAj9LnhmVZW7ROFlQGuJHhqKTQ1EcAfAKhE3wtLwjC/QGU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
